# Site settings
title: A Piece of Sunshine
header-img: "sysimg/autumn2.jpg"
tagline: "一抹阳光"
description: "檐下窗欞斜映枝椏 與你席地對座飲茶"
baseurl: ""
url: "https://shongsu.github.io"

# About/contact
owner:
  name: "Pengyu"
  email: chinhouu1992@gmail.com
  bio: "不以物喜 不以己悲"

# Data
favicon: sysimg/favicon.ico

# Social media
github_username: Shongsu
linkedin_username: in/pengyu-chen-85253886
zhihu_username: Shongsu
gmail_username: chinhouu1992@gmail.com

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

permalink: none
paginate: 8
paginate_path: "/page:num/"

exclude:
  - "less"
  - "node_modules"
  - "Gruntfile.js"
  - "package.json"
  - "README.md"
  - "Gemfile.lock"
  - ".sass-cache"
  - ".jekyll-cache"

# Timezone
timezone: America/Toronto

# Defaults for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Pengyu"
      header-img: "sysimg/autumn2.jpg"

# Comments
comments:
  provider: disqus
  disqus:
    short_name: Shongsu

# Analytics
google_analytics: UA-66863061-1
